language: android
dist: trusty
android:
        components:
                - platform-tools
                - tools
                - build-tools-26.0.1
                - android-26
                - extra-android-m2repository
                - add-on
                - extra
        licenses:
                - 'android-sdk-preview-license-.+'
                - 'android-sdk-license-.+'
                - 'google-gdk-license-.+'
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
               - master
